import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar"
import HeaderForm from "../components/HeaderForm"
import Footer from "../components/Footer"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const blogs= [
    {
    img:"/img1.png",
    title:"How to Interpret the Results of a Satisfaction Survey Scale?",
    author:"Jackie Moncad",
    authorimg:"/Ellipse 2.png"
  },  {
    img:"/img2.png",
    title:"How to Interpret the Results of a Satisfaction Survey Scale?",
    author:"Jackie Moncad",
    authorimg:"/Ellipse 2.png"
  },  {
    img:"/img3.png",
    title:"How to Interpret the Results of a Satisfaction Survey Scale?",
    author:"Jackie Moncad",
    authorimg:"/Ellipse 2.png"
  },  {
    img:"/img4.png",
    title:"How to Interpret the Results of a Satisfaction Survey Scale?",
    author:"Jackie Moncad",
    authorimg:"/Ellipse 2.png"
  }
]
  return (
    <>
      <Head>
        <title>SurveyPaid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/survey.png" />
      </Head>
   

   <div className='bg-[#D7F1FF] h-[500px] relative'>

    <div className='absolute top-0 bottom-0 right-[30%] left-[30%]' style={{zIndex:1}}>
<Image src="/Group 547.png" width={700} height={300} alt="c" style={{zIndex:1}}/>
    </div>
    
    <Navbar/>

    <div className="Header flex items-center justify-center gap-[40px]" style={{zIndex:99999}}>
      <div>
        <p className='text-[#3293FF] font-bold text-sm mb-[20px]'>Over 260,262,166 questions answered!</p>
        <div>
          <h1 className='text-4xl text-[#1C2B38] leading-[50px]'>Cash Money While Browsing<br/>
Through The Internet</h1>
<p className='mt-[30px] mb-[30px] text-sm'>We’ll deposit cash into your account for all the fun things you’re doing online.</p>
        </div>
        <div className="btn"><button className='border-[1px] border-[#80BFFF] p-2 flex items-center justify-center gap-[10px] w-[150px] text-[#62ADFF] text-sm font-bold'> Learn More</button>
        </div>
      </div>

      <div><HeaderForm/></div>
    </div>

    

   
   </div>

   <div className='flex items-center justify-center'>
    <div>
<Image src="/Group 664.png" width={500} height={300} alt="video"/>
    </div>
    <div>
      <p className='text-[#3293FF] font-bold text-sm mb-[10px]'>Millions of survey</p>
      <h2 className='text-3xl text-[#1C2B38] leading-[50px]'>Create Survey For Anything</h2>
      <p className='w-[500px]'>Use our easy and customizable survey platform for hundreds of applications. Here are a just a few</p>
    </div>
   </div>

   <div className='bg-[#2876CC] h-[50px] flex items-center justify-center' style={{borderTopLeftRadius:'40px',borderTopRightRadius:'40px'}}>

    <div className='flex items-center justify-center gap-[20px]'>
      <div><Image src="/Asana-团队协作应用.png" width={100} height={300} alt="video"/></div>
      <div><Image src="/Etrade 亿创理财.png" width={100} height={300} alt="video"/></div>
      <div><Image src="/Walmart.png" width={100} height={300} alt="video"/></div>
      <div><Image src="/Vector.png" width={100} height={300} alt="video"/></div>
      <div><Image src="/Allianz-2.png" width={100} height={300} alt="video"/></div>
    </div>

   </div>

   <div className='bg-[#3293FF] p-4'>
    <div className='flex flex-col items-center justify-center text-white'>
      <div className='mt-[30px]'><h3>We Made Things Easy For You!</h3></div>

      <div className='images flex items-center gap-[20px] mt-[30px]'>
        <div>
        <Image src="/Group 641.png" width={100} height={300} alt="video"/>
        </div>
        <div>
        <Image src="/Group 643.png" width={100} height={300} alt="video"/>
        </div>
        <div>
        <Image src="/Group 644.png" width={100} height={300} alt="video"/>
        </div>
        <div>
        <Image src="/Group 642.png" width={100} height={300} alt="video"/>
        </div>

      </div>

      <div className='worksHeading flex items-center gap-[20px] mt-[30px]'>

        <h1 className='text-5xl font-bold opacity-10'>HOW IT WORKS?</h1>
        <h1 className='text-5xl font-bold'>HOW IT WORKS?</h1>
        <h1 className='text-5xl font-bold opacity-10'>HOW IT WORKS?</h1>

      </div>
      <div><p className='text-center w-[700px] mt-[30px]'>SurveyPaid offers a tremendous set of free tools for designing your survey, sharing your survey online, and reviewing your survey results. We ve got a fantastic user experience and tons of great features.</p></div>
      <div className='bg-white h-[900px] w-[700px] rounded-2xl mt-[30px] relative'>
        <div className='absolute -top-[100px] -right-[60px]'>
        <Image src="/Group 656.png" width={200} height={300} alt="logo"/>
        </div>
        <div className='absolute top-[80px] -left-[120px]'>
        <Image src="/Group 656.png" width={200} height={300} alt="logo"/>
        </div>

        <div className='absolute top-[300px] -right-[120px]'>
        <Image src="/Group 656.png" width={200} height={300} alt="logo"/>
        </div>
        <div className='absolute bottom-0 -right-[120px]'>
        <Image src="/Group 656.png" width={200} height={300} alt="logo"/>
        </div>

        <div className='absolute top-[580px] -left-[120px]'>
        <Image src="/Group 656.png" width={200} height={300} alt="logo"/>
        </div>
      </div>


      <div className='flex gap-[30px] items-center justify-center'>
        <div>
          <Image src="/Group 668.png" width={400} height={300} alt="logo"/>
        </div>
        <div>
          <h2 className='text-3xl font-bold'>Survey Paid Mobile App</h2>
          <p>Available on IOS & Android</p>
          <p className='w-[500px] mt-[30px]'>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.</p>

          <div className='flex gap-[20px]'>
            <div className='bg-white w-[200px] rounded-full h-[50px] flex items-center justify-center gap-[10px] text-[#3293FF] font-bold text-sm'>
              <Image src="/Vector (2).png" width={20} height={50} alt="ios"/> Download For IOS

            </div>
            <div className='bg-white w-[200px] rounded-full h-[50px] flex items-center justify-center gap-[10px] text-[#3293FF] font-bold text-sm'>
              <Image src="/Vector (1).png" width={20} height={50} alt="ios"/> Download For Andriod

            </div>
          </div>
        </div>
      </div>


    </div>

   </div>

<div className='h-[400px] bg-white flex items-center justify-center'>
  <div className='flex flex-col items-center justify-center'>

    <h1 className='font-bold text-3xl'>From The Blog</h1>

    <p>
    Need to put some dummy texts, but I’m exhausted and don’t know what to put. Sorry!
    </p>

    <div className='flex gap-[20px] mt-[20px]'>
    {blogs.map((blog,index)=>{
      return(
        <div key={index}>
          <Image src={blog.img} width={200} height={200} alt="blogimage"/>
          <div className='mt-[10px] flex gap-[10px] items-center'>
          <Image src={blog.authorimg} width={20} height={200} alt="blogimage"/><h4>{blog.author}</h4>
        </div>
        <div><p className='w-[220px] text-sm mt-[10px]'>{blog.title}</p></div>
        </div>
      )
    })}
  </div>

  </div>


 
</div>
     
      
<Footer/>
  
    </>
  )
}
